version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Messaging"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
