name: Cleanup Code

on:
  workflow_dispatch

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  cleanup-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install CleanupCode
        run: dotnet tool install jetbrains.resharper.globaltools --version 2022.1.1 --tool-path ~/bin

      - name: Run CleanupCode
        run: '~/bin/jb cleanupcode --include="**/*.cs;**/*.csproj;**/*.razor;**/*.html;**/*.css;**/*.js;**/*.json" --profile="Built-in: Full Cleanup"'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Cleanup Code
          title: 'Cleanup Code'
          body: >
            This PR is created by cleanup-code.yml GitHub Actions.
