name: Cleanup Code

on:
  workflow_dispatch

jobs:
  cleanup-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CleanupCode
        run: dotnet tool install jetbrains.resharper.globaltools -g --version 2022.1.1

      - name: Run CleanupCode
        run: jb cleanupcode --include="**/*.cs;**/*.csproj;**/*.razor;**/*.html;**/*.css;**/*.js;**/*.json"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Cleanup Code
          title: 'Cleanup Code'
          body: >
            This PR is created by cleanup-code.yml GitHub Actions.
