name: Deploy DotNet project

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform-create:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/terraform-create-resource

    outputs:
      AZURE_RESOURCEGROUP_NAME: ${{ steps.getResourceGroupName.outputs.rgName }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Resource Group name
        id: getResourceGroupName
        run: |
          echo "::set-output name=rgName::$(terraform output -raw rgName)"
  
  fa-build-and-deploy:
    needs: terraform-create
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: test-change-event
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Messaging'
      DOTNET_VERSION: '6.0.x'

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Get Pubilsh Profile
        id: getPublishProfile
        run: |
          echo "::set-output name=PUBLISH_PROFILE::$(az webapp deployment list-publishing-profiles -g '${{ needs.terraform-create.outputs.rgName }}' -n '${{ env.AZURE_FUNCTIONAPP_NAME }}' --xml)"
        
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ steps.getPublishProfile.outputs.PUBLISH_PROFILE }}