name: Terraform remote state

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  terraform:
    name: Setup terraform backend
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/terraform-create-resource

      - name: Terraform Validate
        run: terraform validate 
        working-directory: ./terraform/terraform-create-resource

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform/terraform-create-resource

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/terraform-create-resource