name: Terraform Create Azure Resource

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

permissions:
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      #     client-secret: ${{ secrets.ARM_ClIENT_SECRET }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/terraform-create-resource

      - name: Terraform Validate
        run: terraform validate 
        working-directory: ./terraform/terraform-create-resource

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform/terraform-create-resource

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/terraform-create-resource
